<?php
return [
  '' => [
    'label' => 'Home',
    'section' => 'College',
    'title' => 'Best Dental College in Peshawar | Female BDS — PDC',
    'description' => 'PDC Peshawar: a leading dental college for girls in Peshawar. PM&DC BDS, Peshawar Dental Hospital, KMU admissions, Warsak Road.',
    'priority' => '1.0',
    'changefreq' => 'weekly',
  ],
  'pdc' => [
    'label' => 'Peshawar Dental College',
    'section' => 'College',
    'title' => 'PDC Peshawar | BDS & Peshawar Dental Hospital',
    'description' => 'BDS in Peshawar at PDC — female dental college with Peshawar Dental Hospital, PM&DC/HEC recognition, and clinical training since 2010.',
    'priority' => '0.95',
    'changefreq' => 'monthly',
    'schema' => 'Course',
    'course_name' => 'BDS',
  ],
  'about' => [
    'label' => 'About Us',
    'section' => 'College',
    'title' => 'About PDC | Dental College in Peshawar since 2010',
    'description' => 'About Peshawar Dental College: dental education in Peshawar since 2010, 450+ graduates, PM&DC/HEC recognition, and Peshawar Dental Hospital.',
    'priority' => '0.8',
    'changefreq' => 'monthly',
  ],
  'admissions' => [
    'label' => 'Admissions',
    'section' => 'Academics',
    'title' => 'PDC Admission | KMU BDS for Girls in Peshawar',
    'description' => 'PDC admission for female BDS via KMU and PM&DC. Girls BDS at a private dental college in Peshawar with Peshawar Dental Hospital training.',
    'priority' => '0.9',
    'changefreq' => 'weekly',
    'schema' => 'Course',
    'course_name' => 'BDS',
  ],
  'vision-mission' => [
    'label' => 'Vision & Mission',
    'section' => 'College',
    'title' => 'Vision & Mission | Peshawar Dental College',
    'description' => 'Vision and mission of Peshawar Dental College: ethical, competent dentists for oral health in KP and Pakistan.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'contact' => [
    'label' => 'Contact Us',
    'section' => 'College',
    'title' => 'Contact Peshawar Dental College | Warsak Road',
    'description' => 'Contact Peshawar Dental College, Warsak Road, Peshawar. Phone and email for BDS admissions and enquiries.',
    'priority' => '0.7',
    'changefreq' => 'yearly',
  ],
  'departments' => [
    'label' => 'Departments',
    'section' => 'Academics',
    'title' => 'Orthodontics & Oral Surgery | PDC Peshawar',
    'description' => 'Orthodontics, oral surgery, prosthodontics, and other dental departments at Peshawar Dental College, Peshawar.',
    'priority' => '0.7',
    'changefreq' => 'monthly',
  ],
  'faculty' => [
    'label' => 'Faculty',
    'section' => 'College',
    'title' => 'Faculty | Dental College Peshawar — PDC',
    'description' => 'Faculty of Peshawar Dental College, a leading dental college in Peshawar for BDS teaching and clinical training.',
    'priority' => '0.7',
    'changefreq' => 'monthly',
  ],
  'pg-dental-education' => [
    'label' => 'PG Dental Education',
    'section' => 'Academics',
    'title' => 'Postgraduate Dental Education | PDC Peshawar',
    'description' => 'Postgraduate dental programmes at Peshawar Dental College, Peshawar.',
    'priority' => '0.7',
    'changefreq' => 'monthly',
  ],
  'dental-education' => [
    'label' => 'Dental Education',
    'section' => 'Academics',
    'title' => 'Dental Education | Peshawar Dental College',
    'description' => 'Dental education philosophy and BDS teaching at Peshawar Dental College, Peshawar.',
    'priority' => '0.6',
    'changefreq' => 'yearly',
  ],
  'curriculum' => [
    'label' => 'Curriculum',
    'section' => 'Academics',
    'title' => 'BDS Curriculum | Peshawar Dental College',
    'description' => 'BDS curriculum at Peshawar Dental College: modular dental education aligned with PM&DC in Peshawar.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'pg-curriculum' => [
    'label' => 'PG Curriculum',
    'section' => 'Academics',
    'title' => 'PG Curriculum | Peshawar Dental College',
    'description' => 'Postgraduate dental curriculum at Peshawar Dental College.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'examinations' => [
    'label' => 'Examinations',
    'section' => 'Academics',
    'title' => 'Examinations | Peshawar Dental College',
    'description' => 'Examinations and assessments for BDS students at Peshawar Dental College.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'faculty-research' => [
    'label' => 'Faculty Research',
    'section' => 'Academics',
    'title' => 'Faculty Research | Peshawar Dental College',
    'description' => 'Faculty research at Peshawar Dental College supporting dental scholarship in Peshawar.',
    'priority' => '0.5',
    'changefreq' => 'monthly',
  ],
  'student-guide' => [
    'label' => 'Student Guide',
    'section' => 'Academics',
    'title' => 'Student Guide | Peshawar Dental College',
    'description' => 'Student guide for BDS students at Peshawar Dental College, Peshawar.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'vacant-seats' => [
    'label' => 'Vacant Seats',
    'section' => 'Academics',
    'title' => 'Vacant Seats | Peshawar Dental College',
    'description' => 'Vacant BDS seats and migration information at Peshawar Dental College, Peshawar.',
    'priority' => '0.5',
    'changefreq' => 'monthly',
  ],
  'clinical-skill-labs' => [
    'label' => 'Clinical Skill Labs',
    'section' => 'Academics',
    'title' => 'Clinical Skill Labs | PDC Peshawar',
    'description' => 'Clinical skill labs at Peshawar Dental College for preclinical dental training.',
    'priority' => '0.5',
    'changefreq' => 'yearly',
  ],
  'virtual-museum' => [
    'label' => 'Virtual Museum',
    'section' => 'Academics',
    'title' => 'Virtual Museum | Peshawar Dental College',
    'description' => 'Virtual museum of Peshawar Dental College.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'student-exchange' => [
    'label' => 'Student Exchange',
    'section' => 'Academics',
    'title' => 'Student Exchange | Peshawar Dental College',
    'description' => 'Student exchange opportunities at Peshawar Dental College.',
    'priority' => '0.4',
    'changefreq' => 'yearly',
  ],
  'gallery' => [
    'label' => 'Gallery',
    'section' => 'News',
    'title' => 'Photo Gallery | Peshawar Dental College',
    'description' => 'Photo gallery of Peshawar Dental College campus, clinics, and student life.',
    'priority' => '0.3',
    'changefreq' => 'monthly',
  ],
  'newsletter' => [
    'label' => 'Newsletter',
    'section' => 'News',
    'title' => 'Newsletter | Peshawar Dental College',
    'description' => 'Newsletters from Peshawar Dental College and the Department of Dental Sciences.',
    'priority' => '0.4',
    'changefreq' => 'monthly',
  ],
  'education-literature' => [
    'label' => 'Educational Literature',
    'section' => 'Academics',
    'title' => 'Educational Literature | Peshawar Dental College',
    'description' => 'Educational literature from Peshawar Dental College.',
    'priority' => '0.4',
    'changefreq' => 'monthly',
  ],
  'all-news' => [
    'label' => 'News',
    'section' => 'News',
    'title' => 'News | Peshawar Dental College',
    'description' => 'News from Peshawar Dental College — admissions and campus updates.',
    'priority' => '0.5',
    'changefreq' => 'weekly',
  ],
  'events' => [
    'label' => 'Events',
    'section' => 'News',
    'title' => 'Events | Peshawar Dental College',
    'description' => 'Events at Peshawar Dental College, Peshawar.',
    'priority' => '0.4',
    'changefreq' => 'weekly',
  ],
  'single-news' => [
    'label' => 'News Article',
    'section' => 'News',
    'title' => 'Campus News | Peshawar Dental College',
    'description' => 'News from Peshawar Dental College.',
    'priority' => '0.2',
    'changefreq' => 'monthly',
    'og_type' => 'article',
  ],
  'event-single' => [
    'label' => 'Event',
    'section' => 'News',
    'title' => 'Event | Peshawar Dental College',
    'description' => 'Event details from Peshawar Dental College.',
    'priority' => '0.2',
    'changefreq' => 'monthly',
    'og_type' => 'article',
  ],
  'portal-login' => [
    'label' => 'Portal Login',
    'section' => 'College',
    'title' => 'Portal Login | Peshawar Dental College',
    'description' => 'Portal login for Peshawar Dental College students and staff.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'literary-society' => [
    'label' => 'Literary Society',
    'section' => 'College',
    'title' => 'Literary Society | Peshawar Dental College',
    'description' => 'Literature and arts society at Peshawar Dental College.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'social-welfare' => [
    'label' => 'Social Welfare',
    'section' => 'College',
    'title' => 'Social Welfare Society | Peshawar Dental College',
    'description' => 'Social Welfare Society at Peshawar Dental College.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'sports-society' => [
    'label' => 'Sports Society',
    'section' => 'College',
    'title' => 'Sports Society | Peshawar Dental College',
    'description' => 'Sports society at Peshawar Dental College.',
    'priority' => '0.3',
    'changefreq' => 'yearly',
  ],
  'sitemap-page' => [
    'label' => 'Sitemap',
    'section' => 'College',
    'title' => 'Sitemap | Peshawar Dental College',
    'description' => 'HTML sitemap of Peshawar Dental College and the Department of Dental Sciences.',
    'priority' => '0.3',
    'changefreq' => 'monthly',
  ],
];
